# --- Basic Settings ---
listener 8883
protocol mqtt

# --- Logging (utile pour le debug de l'exercice 4) ---
log_dest stdout
log_type debug
log_type error
log_type warning
log_type notice
log_type information

# --- TLS Configuration (Exercice 2) ---
# Note: Remplace les chemins relatifs par des chemins absolus si nécessaire
cafile ./ca/ca.crt
certfile ./broker/broker.crt
keyfile ./broker/broker.key

# Définit la version minimale pour la sécurité
tls_version tlsv1.2

# --- mTLS Configuration (Exercice 3) ---
# Force le client à présenter un certificat valide
require_certificate true

# Utilise le Common Name (CN) du certificat client comme nom d'utilisateur MQTT
use_identity_as_username true